# Generated by Django 5.0.2 on 2024-03-04 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_about_faq_testimonial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
