# Generated by Django 5.0.2 on 2024-03-20 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_is_coordinator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_coordinator",
        ),
    ]
