# Generated by Django 5.0.2 on 2024-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_regular_user",
            field=models.BooleanField(default=True),
        ),
    ]
