# Generated by Django 5.0.2 on 2024-03-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_userprofile_adoption_status_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
