# Generated by Django 5.0.2 on 2024-03-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coordinator", "0007_bookingappointment_contactsubmission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
