# Generated by Django 5.0.2 on 2024-03-26 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coordinator", "0008_alter_contactmessage_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coordinatorprofile",
            name="adoption_requests",
            field=models.ManyToManyField(blank=True, to="coordinator.adoptionrequest"),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
