# Generated by Django 5.0.2 on 2024-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, upload_to="pets/"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[("Dog", "Dog"), ("Cat", "Cat"), ("Other", "Other")],
                max_length=50,
            ),
        ),
    ]
