# Generated by Django 5.0.2 on 2024-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_description_pet_image_alter_pet_species"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("lost_date", models.DateField()),
                ("location", models.CharField(max_length=200)),
            ],
        ),
    ]
