# Generated by Django 5.0.2 on 2024-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_lostitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("image", models.ImageField(upload_to="found_pets/")),
                ("date_found", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="LostPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("image", models.ImageField(upload_to="lost_pets/")),
                ("date_lost", models.DateField()),
            ],
        ),
    ]
