# Generated by Django 5.0.2 on 2024-02-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_foundpet_lostpet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
