# Generated by Django 5.0.2 on 2024-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0006_adoptionapplication_adoptionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
