# Generated by Django 5.0.2 on 2024-03-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0008_adoptionapplication_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
