# Generated by Django 5.0.2 on 2024-03-05 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0009_contactsubmission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactsubmission",
            name="submission_date",
        ),
    ]
