# Generated by Django 5.0.2 on 2024-04-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0011_alter_contactsubmission_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, upload_to="petss/"),
        ),
    ]
